### Site Settings ###
title               : Tran Hoang
description         : >-
                      Hello, I am Tran - an urban planner-designer, and a landscape enthusiast.
description_en      : >-
                      Hello, I am Tran - an urban planner-designer, and a landscape enthusiast.
description_nl      : >-
                      Hallo, ik ben Tran - een stedenbouwkundige en een liefhebber van landschappen.
url                 : "https://orangeglop.github.io"
baseurl             : ""            # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : Orangeglop/Orangeglop.github.io      # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
open_new_tab        : false                    # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # Paths excluded from navbar
  - pages/404.html
  - pages/index.html


### Author Info ###
author:
  name              : Tran Hoang
  image             : assets/profile.jpg
  email             : tran.hoangnd.kts@gmail.com
  linkedin          : tran-hoang


### Collections ###
collections:
  research:
    output: true


### Analytics (Umami) ###
analytics:
  enabled: true                                         # Set true to enable analytics
  host_url: "https://pulse.2ntense.com"                # Umami instance URL
  website_id: "1260b7a5-8b63-4ed6-bdd1-bc656dc9b00f"    # Umami Website ID

### Build Settings ###
future: true                                            # Publish posts/research even if dated today/tomorrow


### Defaults for collections ###
defaults:
  - scope:
      path: "_research/en"
      type: "research"
    values:
      layout: "post"
      lang: "en"
      permalink: "/en/research/:title/"
  - scope:
      path: "_research/nl"
      type: "research"
    values:
      layout: "post"
      lang: "nl"
      permalink: "/nl/research/:title/"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
